# Generated by Django 3.1.3 on 2020-12-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
